### PR TITLE
Run block to wrap start/stop

### PR DESCRIPTION
**Pull request by Floppy**
I haven't been able to test this on the actual brickpi yet, so caveat emptor for now. I'll post back here when I have.

### CODE REVIEW

**Comment by Floppy** [comment]
confirmed that this does indeed work.

**Comment by Floppy** [comment]
Incidentally, I've kept this separate from the configuration block stuff - if you want both, I'll need to merge that in here and resolve a probably conflict.

**Comment by tehviking** [comment]
Yeah, I merged the other PR before reading this last comment, sorry about that. 
I'd also like to make you a collaborator on the project, though I think we both ought to work in pull requests so someone has eyes on incoming code. 

Thanks James!

**Comment by Floppy** [comment]
Updating it now, no problem - I intended that :)

Would love to be a collaborator - don't worry about me committing to master, I'm well-trained!

**Comment by Floppy** [comment]
This should be good to go now.

**Comment by Floppy** [comment]
And yes, the working-in-PRs thing is how I operate all day every day, so I'm quite used to that. Didn't quite make it clear before :)

**Comment by tehviking** [comment]
Looking good, thanks again James!

**Pull request merged**
